@main def Test =
  println(describe[Int])
  println(describe[List[Int]])
  println(describe[List[String]])
  println(describe[Option[Option[Boolean]]])
  println(describe[Option[String]])
  println(describe[Map[String, Int]])
  println(describe[(Int, String)])
  println(describe[Array[Double]])
  println(describe[Either[String, List[Long]]])
  println(describe[Vector[Char]])
  println(describe[Long])
  println(emptyOf[List[Int]])
  println(emptyOf[Option[String]])
  println(emptyOf[Int])
  println(tupleNames[(Int, String, Boolean)])
  println(tupleNames[EmptyTuple])
  println(sameTwice[(Int, Int)])
  println(sameTwice[Int])
