{
  description = "scalino -- a Scala 3 toolchain that compiles straight to native binaries (no JVM at any step)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  # Wraps the prebuilt release tarball (same one install.sh fetches) rather
  # than rebuilding from source: scalino's own build (build/all.sh) needs
  # vendored/patched scala3+scala-native checkouts, which is a much bigger
  # undertaking to model as a Nix derivation than relinking an
  # already-built, already-relocatable dist/.
  #
  # sources.json (version + per-target sha256) is regenerated by
  # build/10-update-package-metadata.sh after every tagged release -- don't
  # hand-edit it.
  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachSystem [ "x86_64-linux" "aarch64-linux" ] (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        sources = builtins.fromJSON (builtins.readFile ./sources.json);
        target = if system == "x86_64-linux" then "linux-x86_64" else "linux-arm64";
        src = sources.${target};
      in
      {
        packages.default = pkgs.stdenv.mkDerivation {
          pname = "scalino";
          version = sources.version;

          src = pkgs.fetchurl {
            url = "https://github.com/lolgab/scalino/releases/download/v${sources.version}/scalino-v${sources.version}-${target}.tar.gz";
            sha256 = src.sha256;
          };

          nativeBuildInputs = [ pkgs.autoPatchelfHook pkgs.makeWrapper ];
          # scala-native binaries are ordinary dynamically-linked ELF executables
          # (glibc + libc/libm/libpthread), just not built against Nix's own
          # glibc -- autoPatchelfHook rewrites their interpreter/rpath instead
          # of needing a static build.
          buildInputs = with pkgs; [ stdenv.cc.cc.lib zlib zstd ];

          dontConfigure = true;
          dontBuild = true;

          installPhase = ''
            runHook preInstall
            mkdir -p "$out/lib/scalino" "$out/bin"
            cp -a . "$out/lib/scalino/"
            ln -s "$out/lib/scalino/scalino" "$out/bin/scalino"
            ln -s "$out/lib/scalino/scalino-lsp" "$out/bin/scalino-lsp"
            ln -s "$out/lib/scalino/scalino-cs" "$out/bin/scalino-cs"

            # Pre-generated by build/07-build-scalino.sh (see
            # cli/ScalinoCli.scala's `completions` subcommand) and shipped
            # in the tarball -- installed at each shell's own standard
            # lookup path under $out/share, same as any other Nix package.
            mkdir -p "$out/share/bash-completion/completions" \
                     "$out/share/zsh/site-functions" \
                     "$out/share/fish/vendor_completions.d"
            cp "$out/lib/scalino/completions/scalino.bash" "$out/share/bash-completion/completions/scalino"
            cp "$out/lib/scalino/completions/_scalino" "$out/share/zsh/site-functions/_scalino"
            cp "$out/lib/scalino/completions/scalino.fish" "$out/share/fish/vendor_completions.d/scalino.fish"
            runHook postInstall
          '';

          # clang and llvm-info is a hard runtime dependency (scala-native always links
          # through it, even for a zero-dependency Hello World) -- wrap the
          # binaries so it's on PATH without polluting the caller's own env.
          postFixup = ''
            wrapProgram "$out/bin/scalino" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.clang pkgs.llvmPackages.llvm.dev ]}
            wrapProgram "$out/bin/scalino-lsp" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.clang pkgs.llvmPackages.llvm.dev ]}
          '';

          meta = with pkgs.lib; {
            description = "Scala 3 toolchain that compiles straight to native binaries -- no JVM at any step";
            homepage = "https://github.com/lolgab/scalino";
            license = licenses.asl20;
            platforms = [ "x86_64-linux" "aarch64-linux" ];
            mainProgram = "scalino";
          };
        };

        apps.default = flake-utils.lib.mkApp { drv = self.packages.${system}.default; };
      });
}
