{
  description = "scalino -- a Scala 3 toolchain that compiles straight to native binaries (no JVM at any step)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  # Wraps the prebuilt release tarball (same one install.sh fetches) rather
  # than rebuilding from source: scalino's own build (build/all.sh) needs
  # vendored/patched scala3+scala-native checkouts, which is a much bigger
  # undertaking to model as a Nix derivation than relinking an
  # already-built, already-relocatable dist/.
  #
  # sources.json (version + per-target sha256) is regenerated by
  # build/10-update-package-metadata.sh after every tagged release -- don't
  # hand-edit it.
  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachSystem [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ] (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        sources = builtins.fromJSON (builtins.readFile ./sources.json);
        target = {
          x86_64-linux = "linux-x86_64";
          aarch64-linux = "linux-arm64";
          x86_64-darwin = "macos-x86_64";
          aarch64-darwin = "macos-arm64";
        }.${system};
        src = sources.${target};
        # scalino-lsp's go-to-definition into scala-library/scala3-library
        # looks for <jar>-sources.jar next to the stdlib jars in dist/lib. The
        # CLI would normally download them on first `setup-ide`, but a store
        # path is read-only, so they are fetched (and hash-pinned) here.
        stdlibSources = pkgs.lib.mapAttrsToList
          (name: v: {
            inherit name;
            jar = pkgs.fetchurl {
              url = "https://repo1.maven.org/maven2/org/scala-lang/${name}/${sources.scalaVersion}/${name}-${sources.scalaVersion}-sources.jar";
              sha256 = v.sha256;
            };
          })
          sources.stdlibSources;
      in
      {
        packages.default = pkgs.stdenv.mkDerivation {
          pname = "scalino";
          version = sources.version;

          src = pkgs.fetchurl {
            url = "https://github.com/lolgab/scalino/releases/download/v${sources.version}/scalino-v${sources.version}-${target}.tar.gz";
            sha256 = src.sha256;
          };

          nativeBuildInputs = [ pkgs.makeWrapper ] ++ pkgs.lib.optionals pkgs.stdenv.isLinux [ pkgs.autoPatchelfHook ];
          # Linux: scala-native binaries are ordinary dynamically-linked ELF
          # executables (glibc + libc/libm/libpthread), just not built against
          # Nix's own glibc -- autoPatchelfHook rewrites their interpreter/rpath
          # instead of needing a static build. macOS: the Mach-O binaries only
          # link system libraries (libSystem, libz), so nothing to patch.
          buildInputs = pkgs.lib.optionals pkgs.stdenv.isLinux (with pkgs; [ stdenv.cc.cc.lib zlib zstd ]);

          dontConfigure = true;
          dontBuild = true;

          installPhase = ''
            runHook preInstall
            mkdir -p "$out/lib/scalino" "$out/bin"
            cp -a . "$out/lib/scalino/"
            ln -s "$out/lib/scalino/scalino" "$out/bin/scalino"
            ln -s "$out/lib/scalino/scalino-lsp" "$out/bin/scalino-lsp"
            ln -s "$out/lib/scalino/scalino-cs" "$out/bin/scalino-cs"

            ${pkgs.lib.concatMapStringsSep "\n" (s: ''
              cp ${s.jar} "$out/lib/scalino/lib/${s.name}-${sources.scalaVersion}-sources.jar"
            '') stdlibSources}

            # Pre-generated by build/07-build-scalino.sh (see
            # cli/ScalinoCli.scala's `completions` subcommand) and shipped
            # in the tarball -- installed at each shell's own standard
            # lookup path under $out/share, same as any other Nix package.
            mkdir -p "$out/share/bash-completion/completions" \
                     "$out/share/zsh/site-functions" \
                     "$out/share/fish/vendor_completions.d"
            cp "$out/lib/scalino/completions/scalino.bash" "$out/share/bash-completion/completions/scalino"
            cp "$out/lib/scalino/completions/_scalino" "$out/share/zsh/site-functions/_scalino"
            cp "$out/lib/scalino/completions/scalino.fish" "$out/share/fish/vendor_completions.d/scalino.fish"
            runHook postInstall
          '';

          # clang and llvm-info is a hard runtime dependency (scala-native always links
          # through it, even for a zero-dependency Hello World) -- wrap the
          # binaries so it's on PATH without polluting the caller's own env.
          postFixup = ''
            wrapProgram "$out/bin/scalino" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.clang pkgs.llvmPackages.llvm.dev ]}
            wrapProgram "$out/bin/scalino-lsp" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.clang pkgs.llvmPackages.llvm.dev ]}
          '';

          meta = with pkgs.lib; {
            description = "Scala 3 toolchain that compiles straight to native binaries -- no JVM at any step";
            homepage = "https://github.com/lolgab/scalino";
            license = licenses.asl20;
            platforms = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
            mainProgram = "scalino";
          };
        };

        apps.default = flake-utils.lib.mkApp { drv = self.packages.${system}.default; };

        # Building *with* scalino inside the Nix sandbox (no network).
        #
        # Nix forbids network access during a build, except in fixed-output
        # derivations (the output hash is declared up front). So dependencies
        # follow the usual lockfile -> one fixed-output fetch per artifact ->
        # offline build scheme (same as importCargoLock for Rust):
        #
        #   1. in your project:  scalino lock .     # writes scalino.lock.json
        #   2. commit scalino.lock.json
        #   3. in your flake:    scalino.lib.${system}.mkScalinoApp { ... }
        #
        # mkScalinoCache turns the lock into a coursier-layout cache dir (one
        # pkgs.fetchurl per jar, linked at its cache-relative path); mkScalinoApp
        # builds with SCALINO_CACHE pointing there and SCALINO_OFFLINE=1.
        lib = rec {
          # Emit "<kind> <flag>" per line, then rebuild the flags in Nix. The
          # indirection keeps arbitrary flag text (spaces, quotes, Nix punctuation)
          # out of Nix's string syntax, where shell-style quoting does not survive.
          pkgConfigArgs =
            { name
            , buildInputs
            , modules
            }:
            let
              flagFile = pkgs.runCommandCC "${name}-native-flags" {
                inherit buildInputs;
                nativeBuildInputs = [ pkgs.pkg-config ];
                dontFixup = true;
              } ''
                for m in ${lib.escapeShellArgs modules}; do
                  for f in $(pkg-config --cflags "$m"); do echo "c $f"; done
                  for f in $(pkg-config --libs "$m"); do echo "l $f"; done
                done > $out
              '';

              lines = lib.filter (l: l != "") (lib.splitString "\n" (builtins.readFile flagFile));

              toFlag = l:
                let parts = lib.splitString " " l;
                in if builtins.head parts == "c"
                then [ "--native-c-compile" (lib.last parts) ]
                else [ "--native-linking" (lib.last parts) ];
            in lib.concatMap toFlag lines;

          # withSources also fetches the -sources.jar files `scalino lock`
          # recorded; they land next to their classes jars, which is where
          # scalino-lsp looks (go-to-definition into library code).
          mkScalinoCache = { lockFile, withSources ? false }:
            let
              lock = builtins.fromJSON (builtins.readFile lockFile);
              all = pkgs.lib.concatMap
                (s: s.artifacts ++ pkgs.lib.optionals withSources (s.sources or [ ]))
                (pkgs.lib.attrValues lock.sets);
              remote = builtins.filter (a: !(a.local or false)) all;
              # dependency sets overlap; one entry per cache path
              unique = pkgs.lib.attrValues (pkgs.lib.listToAttrs (map (a: { name = a.path; value = a; }) remote));
            in
            if builtins.length remote != builtins.length all
            then throw "scalino.lock.json has machine-local (file: repository) artifacts, which Nix cannot fetch -- publish them to a real repository"
            else pkgs.linkFarm "scalino-deps-cache" (map
              (a: {
                name = a.path;
                path = pkgs.fetchurl { inherit (a) url sha256; };
              })
              unique);

          mkScalinoApp =
            { pname
            , version ? "0.0.0"
            , src
            , lockFile ? src + "/scalino.lock.json"
            , sources ? [ "." ]
            , extraArgs ? [ ]  # e.g. [ "--native-mode" "release-fast" ]
            , buildInputs ? [ ]        # native libs; also what pkgConfig queries
            , nativeBuildInputs ? [ ]  # extra build-time tools (pkg-config is added)
            , pkgConfig ? [ ]          # pkg-config modules: cflags for C sources, libs for linking
            }:
            let
              pkgArgs = lib.optionals (pkgConfig != [ ])
                (pkgConfigArgs { name = pname; inherit buildInputs; modules = pkgConfig; });
            in pkgs.clangStdenv.mkDerivation {
              inherit pname version src buildInputs;
              nativeBuildInputs = [ self.packages.${pkgs.stdenv.hostPlatform.system}.default ]
                ++ nativeBuildInputs;
              env = {
                SCALINO_CACHE = "${mkScalinoCache { inherit lockFile; }}";
                SCALINO_OFFLINE = "1";
              };
              dontConfigure = true;
              buildPhase = ''
                runHook preBuild
                export HOME="$TMPDIR"
                scalino package ${pkgs.lib.escapeShellArgs sources} --offline -o app \
                  ${pkgs.lib.escapeShellArgs (extraArgs ++ pkgArgs)}
                runHook postBuild
              '';
              installPhase = ''
                runHook preInstall
                install -Dm755 app "$out/bin/${pname}"
                runHook postInstall
              '';
            };

          # `nix develop` shell for editing: scalino plus a cache that includes
          # sources jars, so `scalino setup-ide .` (-> .scalino-build/
          # scalino-lsp.json) and scalino-lsp work with no network. The cache
          # is a read-only store path and SCALINO_OFFLINE=1, so after changing
          # dependencies re-lock with a writable cache:
          #   SCALINO_OFFLINE=0 SCALINO_CACHE= scalino lock .
          # then let Nix rebuild the shell from the new lockfile.
          mkScalinoDevShell = { lockFile, packages ? [ ] }:
            pkgs.mkShell {
              packages = [ self.packages.${system}.default ] ++ packages;
              env = {
                SCALINO_CACHE = "${mkScalinoCache { inherit lockFile; withSources = true; }}";
                SCALINO_OFFLINE = "1";
              };
            };
        };
      });
}
