{
  description = "scalino -- a Scala 3 toolchain that compiles straight to native binaries (no JVM at any step)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  # Wraps the prebuilt release tarball (same one install.sh fetches) rather
  # than rebuilding from source: scalino's own build (build/all.sh) needs a
  # transient GraalVM native-image step and vendored/patched scala3+scala-native
  # checkouts, which is a much bigger undertaking to model as a Nix
  # derivation than relinking an already-built, already-relocatable dist/.
  #
  # sources.json (version + per-target sha256) is regenerated by
  # build/10-update-package-metadata.sh after every tagged release -- don't
  # hand-edit it.
  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachSystem [ "x86_64-linux" "aarch64-linux" ] (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        sources = builtins.fromJSON (builtins.readFile ./sources.json);
        target = if system == "x86_64-linux" then "linux-x86_64" else "linux-arm64";
        src = sources.${target};
      in
      {
        packages.default = pkgs.stdenv.mkDerivation {
          pname = "scalino";
          version = sources.version;

          src = pkgs.fetchurl {
            url = "https://github.com/lolgab/scalino/releases/download/v${sources.version}/scalino-v${sources.version}-${target}.tar.gz";
            sha256 = src.sha256;
          };

          nativeBuildInputs = [ pkgs.autoPatchelfHook pkgs.makeWrapper ];
          # scala-native binaries are ordinary dynamically-linked ELF executables
          # (glibc + libc/libm/libpthread), just not built against Nix's own
          # glibc -- autoPatchelfHook rewrites their interpreter/rpath instead
          # of needing a static build.
          buildInputs = [ pkgs.stdenv.cc.cc.lib ];

          dontConfigure = true;
          dontBuild = true;

          installPhase = ''
            runHook preInstall
            mkdir -p "$out/lib/scalino" "$out/bin"
            cp -a . "$out/lib/scalino/"
            ln -s "$out/lib/scalino/scalino" "$out/bin/scalino"
            ln -s "$out/lib/scalino/scalino-lsp" "$out/bin/scalino-lsp"
            runHook postInstall
          '';

          # clang is a hard runtime dependency (scala-native always links
          # through it, even for a zero-dependency Hello World) -- wrap the
          # binaries so it's on PATH without polluting the caller's own env.
          postFixup = ''
            wrapProgram "$out/bin/scalino" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.clang ]}
            wrapProgram "$out/bin/scalino-lsp" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.clang ]}
          '';

          meta = with pkgs.lib; {
            description = "Scala 3 toolchain that compiles straight to native binaries -- no JVM at any step";
            homepage = "https://github.com/lolgab/scalino";
            license = licenses.asl20;
            platforms = [ "x86_64-linux" "aarch64-linux" ];
            mainProgram = "scalino";
          };
        };

        apps.default = flake-utils.lib.mkApp { drv = self.packages.${system}.default; };
      });
}
