# Homebrew formula for a custom tap (e.g. lolgab/homebrew-scalino), not
# homebrew-core -- core requires building from source, and scalino's own
# build (build/all.sh) needs vendored/patched scala3+scala-native checkouts
# that don't fit homebrew-core's "build from source in a sandbox" model.
# This formula just installs the prebuilt, already-relocatable release
# tarball, same one install.sh fetches.
#
# url/sha256 below are regenerated by build/10-update-package-metadata.sh
# after every tagged release -- don't hand-edit them.
class Scalino < Formula
  desc "Scala 3 toolchain that compiles straight to native binaries -- no JVM at any step"
  homepage "https://github.com/lolgab/scalino"
  version "0.0.14"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-macos-x86_64.tar.gz"
      sha256 "27d717239e0ec2ff2642e864f335a7f0da9f9971d87cfd86be8dab5e5331d63c"
    end
    on_arm do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-macos-arm64.tar.gz"
      sha256 "9d672c434afd5feb4fe8b535883eabec07ac3f264d1761618ebe641f1eefe7e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-linux-x86_64.tar.gz"
      sha256 "94006b66fd481e2a42393af11206d7f6adbca135188f2a63b711815a662a445e"
    end
    on_arm do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-linux-arm64.tar.gz"
      sha256 "b44385a9e6f0781284cf15c674ca62192d536d22eeb97924809aea51bbf35183"
    end
  end

  depends_on "llvm" => :recommended # provides clang/clang++ where the OS doesn't already (Linux); macOS uses Xcode CLT's own
  # coursier's `cs` launcher (needed for `//> using dep`) is bundled in the
  # tarball as scalino-cs -- no separate dependency.

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"scalino"
    bin.install_symlink libexec/"scalino-lsp"
    bin.install_symlink libexec/"scalino-cs"

    # Pre-generated by build/07-build-scalino.sh (see cli/ScalinoCli.scala's
    # `completions` subcommand) and shipped in the tarball -- installed
    # straight from there rather than shelling out to the just-installed
    # binary, so this works identically whether or not the formula is
    # actually run on the machine it was built for.
    bash_completion.install libexec/"completions/scalino.bash" => "scalino"
    zsh_completion.install libexec/"completions/_scalino"
    fish_completion.install libexec/"completions/scalino.fish"
  end

  test do
    system "#{bin}/scalino", "--help"
  end
end
