# Homebrew formula for a custom tap (e.g. lolgab/homebrew-scalino), not
# homebrew-core -- core requires building from source, and scalino's own
# build (build/all.sh) needs vendored/patched scala3+scala-native checkouts
# that don't fit homebrew-core's "build from source in a sandbox" model.
# This formula just installs the prebuilt, already-relocatable release
# tarball, same one install.sh fetches.
#
# url/sha256 below are regenerated by build/10-update-package-metadata.sh
# after every tagged release -- don't hand-edit them.
class Scalino < Formula
  desc "Scala 3 toolchain that compiles straight to native binaries -- no JVM at any step"
  homepage "https://github.com/lolgab/scalino"
  version "0.0.17"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-macos-x86_64.tar.gz"
      sha256 "a962fa20d40f2a9ac5d12e07b7d0c5a68e87ba76b2f338842daf733754dbadb6"
    end
    on_arm do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-macos-arm64.tar.gz"
      sha256 "2a771e117d90054b7814ed5007d778a5b1a71e54e88e5fa812af0b5bce01ef52"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-linux-x86_64.tar.gz"
      sha256 "507b316ba67b4f1dc0d95c9ea7ea006404ebfb04a1762f78153c28596ccef157"
    end
    on_arm do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-linux-arm64.tar.gz"
      sha256 "ab731590e77dd8ec7abcd15f2e2e59cd278559ea2da0c0d5ae030b7f70d42c3f"
    end
  end

  depends_on "llvm" => :recommended # provides clang/clang++ where the OS doesn't already (Linux); macOS uses Xcode CLT's own
  # coursier's `cs` launcher (needed for `//> using dep`) is bundled in the
  # tarball as scalino-cs -- no separate dependency.

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"scalino"
    bin.install_symlink libexec/"scalino-lsp"
    bin.install_symlink libexec/"scalino-cs"

    # Pre-generated by build/07-build-scalino.sh (see cli/ScalinoCli.scala's
    # `completions` subcommand) and shipped in the tarball -- installed
    # straight from there rather than shelling out to the just-installed
    # binary, so this works identically whether or not the formula is
    # actually run on the machine it was built for.
    bash_completion.install libexec/"completions/scalino.bash" => "scalino"
    zsh_completion.install libexec/"completions/_scalino"
    fish_completion.install libexec/"completions/scalino.fish"
  end

  test do
    system "#{bin}/scalino", "--help"
  end
end
