# Homebrew formula for a custom tap (e.g. lolgab/homebrew-scalino), not
# homebrew-core -- core requires building from source, and scalino's own
# build (build/all.sh) needs vendored/patched scala3+scala-native checkouts
# that don't fit homebrew-core's "build from source in a sandbox" model.
# This formula just installs the prebuilt, already-relocatable release
# tarball, same one install.sh fetches.
#
# url/sha256 below are regenerated by build/10-update-package-metadata.sh
# after every tagged release -- don't hand-edit them.
class Scalino < Formula
  desc "Scala 3 toolchain that compiles straight to native binaries -- no JVM at any step"
  homepage "https://github.com/lolgab/scalino"
  version "0.0.21"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-macos-x86_64.tar.gz"
      sha256 "a93693b3e2a10e2502ba0a7e3ca186e493764c45ab940cbcb6d06b3d2732d4c1"
    end
    on_arm do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-macos-arm64.tar.gz"
      sha256 "8cbb1aa0e6d8870fc122815cd5d151ebdedd6507dd00a9bd0edc81950211b011"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-linux-x86_64.tar.gz"
      sha256 "432e53f4c2bc6868bc118f08dd081585ec6f46c2c0b106c0c4385de5813fb146"
    end
    on_arm do
      url "https://github.com/lolgab/scalino/releases/download/v#{version}/scalino-v#{version}-linux-arm64.tar.gz"
      sha256 "0d364b4b45a5b3043925a4e72add3fe9ad3e1829a1e2ac75f4a136047bbca42f"
    end
  end

  depends_on "llvm" => :recommended # provides clang/clang++ where the OS doesn't already (Linux); macOS uses Xcode CLT's own
  # coursier's `cs` launcher (needed for `//> using dep`) is bundled in the
  # tarball as scalino-cs -- no separate dependency.

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"scalino"
    bin.install_symlink libexec/"scalino-lsp"
    bin.install_symlink libexec/"scalino-cs"

    # Pre-generated by build/07-build-scalino.sh (see cli/ScalinoCli.scala's
    # `completions` subcommand) and shipped in the tarball -- installed
    # straight from there rather than shelling out to the just-installed
    # binary, so this works identically whether or not the formula is
    # actually run on the machine it was built for.
    bash_completion.install libexec/"completions/scalino.bash" => "scalino"
    zsh_completion.install libexec/"completions/_scalino"
    fish_completion.install libexec/"completions/scalino.fish"
  end

  test do
    system "#{bin}/scalino", "--help"
  end
end
